 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package findthem;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JButton;

import javax.swing.Timer;

/**
 *
 * @author frien
 */
public class Finding extends javax.swing.JFrame {

    /**
     * Creates new form Finding
     */
    
    public Finding() {
        initComponents();
        icons();
        
      
    }
    
    
    JButton b;
    JButton prevButton;
    boolean openIcon=false;
    String hideIcon;
    boolean whenClick=false;
    
    Timer t1 =new Timer(1000,new ActionListener(){
        
        @Override
        public void actionPerformed(ActionEvent e){
            
         //   b.setIcon(null);
         //   prevButton.setIcon(null)
            b.setEnabled(false);
            prevButton.setEnabled(false);
            whenClick=false;
            openIcon=false;
            
            
        }
        
    });
    Timer t2 =new Timer(1000,new ActionListener(){
        
        @Override
        public void actionPerformed(ActionEvent e){
            
         //   b.setIcon(null);
         //   prevButton.setIcon(null)
            b.setIcon(null);
            prevButton.setIcon(null);
            whenClick=false;
            openIcon=false;
            
        }
        
    });
    
    
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton10.setBackground(new java.awt.Color(255, 0, 0));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everythingInOneAction(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 255, 0));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everythingInOneAction(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(255, 255, 102));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everythingInOneAction(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(255, 255, 51));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everythingInOneAction(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(255, 255, 153));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everythingInOneAction(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(255, 255, 204));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everythingInOneAction(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(102, 255, 102));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everythingInOneAction(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(153, 255, 153));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everythingInOneAction(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(204, 255, 204));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everythingInOneAction(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 240));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everythingInOneAction(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 0, 255));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everythingInOneAction(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everythingInOneAction(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 153, 255));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everythingInOneAction(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everythingInOneAction(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 204, 204));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everythingInOneAction(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 153, 153));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everythingInOneAction(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 102, 102));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everythingInOneAction(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(51, 255, 51));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everythingInOneAction(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 51, 51));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everythingInOneAction(evt);
            }
        });

        jButton20.setBackground(new java.awt.Color(0, 255, 0));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everythingInOneAction(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void everythingInOneAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_everythingInOneAction
         
         if(whenClick==false)
         {
             b=(JButton)evt.getSource();
             
              if(jButton1.equals(b))
        {
            jButton1.setIcon(icon[keep[0]]);
            if(openIcon==false)
            {
                hideIcon=icon[keep[0]].toString();
                openIcon = true;
                prevButton=b;
            }
            else if(openIcon==true && !prevButton.equals(b))
            {
                whenClick=true;
                if(hideIcon==icon[keep[0]].toString())
                {
                    t1.setRepeats(false);
                    t1.start();
                }
                else
                {
                    t2.setRepeats(false);
                    t2.start();
                }
            }
        }
        else if(jButton2.equals(b))
        {
            jButton2.setIcon(icon[keep[1]]);
            if(openIcon==false)
            {
                hideIcon=icon[keep[1]].toString();
                openIcon = true;
                prevButton=b;
            }
            else if(openIcon==true && !prevButton.equals(b))
            {
                                whenClick=true;

                if(hideIcon==icon[keep[1]].toString())
                {
                    t1.setRepeats(false);
                    t1.start();
                }
                else
                {
                    t2.setRepeats(false);
                    t2.start();
                }
            }
        }
        else if(jButton3.equals(b))
        {
            jButton3.setIcon(icon[keep[2]]);
            if(openIcon==false)
            {
                hideIcon=icon[keep[2]].toString();
                openIcon = true;
                prevButton=b;
            }
            else if(openIcon==true && !prevButton.equals(b))
            {
                                whenClick=true;

                if(hideIcon==icon[keep[2]].toString())
                {
                    t1.setRepeats(false);
                    t1.start();
                }
                else
                {
                    t2.setRepeats(false);
                    t2.start();
                }
            }
        }
              else if(jButton4.equals(b))
        {
            jButton4.setIcon(icon[keep[3]]);
            if(openIcon==false)
            {
                hideIcon=icon[keep[3]].toString();
                openIcon = true;
                prevButton=b;
            }
            else if(openIcon==true && !prevButton.equals(b))
            {
                                whenClick=true;

                if(hideIcon==icon[keep[3]].toString())
                {
                    t1.setRepeats(false);
                    t1.start();
                }
                else
                {
                    t2.setRepeats(false);
                    t2.start();
                }
            }
        }
              else if(jButton5.equals(b))
        {
            jButton5.setIcon(icon[keep[4]]);
            if(openIcon==false)
            {
                hideIcon=icon[keep[4]].toString();
                openIcon = true;
                prevButton=b;
            }
            else if(openIcon==true && !prevButton.equals(b))
            {
                                whenClick=true;

                if(hideIcon==icon[keep[4]].toString())
                {
                    t1.setRepeats(false);
                    t1.start();
                }
                else
                {
                    t2.setRepeats(false);
                    t2.start();
                }
            }
        }
              else if(jButton6.equals(b))
        {
            jButton6.setIcon(icon[keep[5]]);
            if(openIcon==false)
            {
                hideIcon=icon[keep[5]].toString();
                openIcon = true;
                prevButton=b;
            }
            else if(openIcon==true && !prevButton.equals(b))
            {
                                whenClick=true;

                if(hideIcon==icon[keep[5]].toString())
                {
                    t1.setRepeats(false);
                    t1.start();
                }
                else
                {
                    t2.setRepeats(false);
                    t2.start();
                }
            }
        }
              else if(jButton7.equals(b))
        {
            jButton7.setIcon(icon[keep[6]]);
            if(openIcon==false)
            {
                hideIcon=icon[keep[6]].toString();
                openIcon = true;
                prevButton=b;
            }
            else if(openIcon==true && !prevButton.equals(b))
            {
                                whenClick=true;

                if(hideIcon==icon[keep[6]].toString())
                {
                    t1.setRepeats(false);
                    t1.start();
                }
                else
                {
                    t2.setRepeats(false);
                    t2.start();
                }
            }
        }
              else if(jButton8.equals(b))
        {
            jButton8.setIcon(icon[keep[7]]);
            if(openIcon==false)
            {
                hideIcon=icon[keep[7]].toString();
                openIcon = true;
                prevButton=b;
            }
            else if(openIcon==true && !prevButton.equals(b))
            {
                                whenClick=true;

                if(hideIcon==icon[keep[7]].toString())
                {
                    t1.setRepeats(false);
                    t1.start();
                }
                else
                {
                    t2.setRepeats(false);
                    t2.start();
                }
            }
        }
              else if(jButton9.equals(b))
        {
            jButton9.setIcon(icon[keep[8]]);
            if(openIcon==false)
            {
                hideIcon=icon[keep[8]].toString();
                openIcon = true;
                prevButton=b;
            }
            else if(openIcon==true && !prevButton.equals(b))
            {
                                whenClick=true;

                if(hideIcon==icon[keep[8]].toString())
                {
                    t1.setRepeats(false);
                    t1.start();
                }
                else
                {
                    t2.setRepeats(false);
                    t2.start();
                }
            }
        }
              else if(jButton10.equals(b))
        {
            jButton10.setIcon(icon[keep[9]]);
            if(openIcon==false)
            {
                hideIcon=icon[keep[9]].toString();
                openIcon = true;
                prevButton=b;
            }
            else if(openIcon==true && !prevButton.equals(b))
            {
                                whenClick=true;

                if(hideIcon==icon[keep[9]].toString())
                {
                    t1.setRepeats(false);
                    t1.start();
                }
                else
                {
                    t2.setRepeats(false);
                    t2.start();
                }
            }
        }
              else if(jButton11.equals(b))
        {
            jButton11.setIcon(icon[keep[10]]);
            if(openIcon==false)
            {
                hideIcon=icon[keep[10]].toString();
                openIcon = true;
                prevButton=b;
            }
            else if(openIcon==true && !prevButton.equals(b))
            {
                                whenClick=true;

                if(hideIcon==icon[keep[10]].toString())
                {
                    t1.setRepeats(false);
                    t1.start();
                }
                else
                {
                    t2.setRepeats(false);
                    t2.start();
                }
            }
        }
              else if(jButton12.equals(b))
        {
            jButton12.setIcon(icon[keep[11]]);
            if(openIcon==false)
            {
                hideIcon=icon[keep[11]].toString();
                openIcon = true;
                prevButton=b;
            }
            else if(openIcon==true && !prevButton.equals(b))
            {
                                whenClick=true;

                if(hideIcon==icon[keep[11]].toString())
                {
                    t1.setRepeats(false);
                    t1.start();
                }
                else
                {
                    t2.setRepeats(false);
                    t2.start();
                }
            }
        }
              else if(jButton13.equals(b))
        {
            jButton13.setIcon(icon[keep[12]]);
            if(openIcon==false)
            {
                hideIcon=icon[keep[12]].toString();
                openIcon = true;
                prevButton=b;
            }
            else if(openIcon==true && !prevButton.equals(b))
            {
                                whenClick=true;

                if(hideIcon==icon[keep[12]].toString())
                {
                    t1.setRepeats(false);
                    t1.start();
                }
                else
                {
                    t2.setRepeats(false);
                    t2.start();
                }
            }
        }
              else if(jButton14.equals(b))
        {
            jButton14.setIcon(icon[keep[13]]);
            if(openIcon==false)
            {
                hideIcon=icon[keep[13]].toString();
                openIcon = true;
                prevButton=b;
            }
            else if(openIcon==true && !prevButton.equals(b))
            {
                                whenClick=true;

                if(hideIcon==icon[keep[13]].toString())
                {
                    t1.setRepeats(false);
                    t1.start();
                }
                else
                {
                    t2.setRepeats(false);
                    t2.start();
                }
            }
        }
              else if(jButton15.equals(b))
        {
            jButton15.setIcon(icon[keep[14]]);
            if(openIcon==false)
            {
                hideIcon=icon[keep[14]].toString();
                openIcon = true;
                prevButton=b;
            }
            else if(openIcon==true && !prevButton.equals(b))
            {
                                whenClick=true;

                if(hideIcon==icon[keep[14]].toString())
                {
                    t1.setRepeats(false);
                    t1.start();
                }
                else
                {
                    t2.setRepeats(false);
                    t2.start();
                }
            }
        }
              else if(jButton16.equals(b))
        {
            jButton16.setIcon(icon[keep[15]]);
            if(openIcon==false)
            {
                hideIcon=icon[keep[15]].toString();
                openIcon = true;
                prevButton=b;
            }
            else if(openIcon==true && !prevButton.equals(b))
            {
                                whenClick=true;

                if(hideIcon==icon[keep[15]].toString())
                {
                    t1.setRepeats(false);
                    t1.start();
                }
                else
                {
                    t2.setRepeats(false);
                    t2.start();
                }
            }
        }
              else if(jButton17.equals(b))
        {
            jButton17.setIcon(icon[keep[16]]);
            if(openIcon==false)
            {
                hideIcon=icon[keep[16]].toString();
                openIcon = true;
                prevButton=b;
            }
            else if(openIcon==true && !prevButton.equals(b))
            {
                                whenClick=true;

                if(hideIcon==icon[keep[16]].toString())
                {
                    t1.setRepeats(false);
                    t1.start();
                }
                else
                {
                    t2.setRepeats(false);
                    t2.start();
                }
            }
        }
              else if(jButton18.equals(b))
        {
            jButton18.setIcon(icon[keep[17]]);
            if(openIcon==false)
            {
                hideIcon=icon[keep[17]].toString();
                openIcon = true;
                prevButton=b;
            }
            else if(openIcon==true && !prevButton.equals(b))
            {
                                whenClick=true;

                if(hideIcon==icon[keep[17]].toString())
                {
                    t1.setRepeats(false);
                    t1.start();
                }
                else
                {
                    t2.setRepeats(false);
                    t2.start();
                }
            }
        }
              else if(jButton19.equals(b))
        {
            jButton19.setIcon(icon[keep[18]]);
            if(openIcon==false)
            {
                hideIcon=icon[keep[18]].toString();
                openIcon = true;
                prevButton=b;
            }
            else if(openIcon==true && !prevButton.equals(b))
            {
                                whenClick=true;

                if(hideIcon==icon[keep[18]].toString())
                {
                    t1.setRepeats(false);
                    t1.start();
                }
                else
                {
                    t2.setRepeats(false);
                    t2.start();
                }
            }
        }
              else if(jButton20.equals(b))
        {
            jButton20.setIcon(icon[keep[19]]);
            if(openIcon==false)
            {
                hideIcon=icon[keep[19]].toString();
                openIcon = true;
                prevButton=b;
            }
            else if(openIcon==true && !prevButton.equals(b))
            {
                                whenClick=true;

                if(hideIcon==icon[keep[19]].toString())
                {
                    t1.setRepeats(false);
                    t1.start();
                }
                else
                {
                    t2.setRepeats(false);
                    t2.start();
                }
            }
        }
              
         }
       
    }//GEN-LAST:event_everythingInOneAction
 
  
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Finding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Finding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Finding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Finding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Finding().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables

   ImageIcon [] icon= new ImageIcon[20];
    int [] keep =new int[20];
    private void icons() {
            icon[0]= new ImageIcon("icon/1.png");
            icon[1]= new ImageIcon("icon/1.png");
            icon[2]= new ImageIcon("icon/2.png");
            icon[3]= new ImageIcon("icon/2.png");
            icon[4]= new ImageIcon("icon/3.png");
            icon[5]= new ImageIcon("icon/3.png");
            icon[6]= new ImageIcon("icon/4.png");
            icon[7]= new ImageIcon("icon/4.png");
            icon[8]= new ImageIcon("icon/5.png");
            icon[9]= new ImageIcon("icon/5.png");
            icon[10]= new ImageIcon("icon/6.png");
            icon[11]= new ImageIcon("icon/6.png");
            icon[12]= new ImageIcon("icon/7.png");
            icon[13]= new ImageIcon("icon/7.png");
            icon[14]= new ImageIcon("icon/8.png");
            icon[15]= new ImageIcon("icon/8.png");
            icon[16]= new ImageIcon("icon/9.png");
            icon[17]= new ImageIcon("icon/9.png");
            icon[18]= new ImageIcon("icon/10.png");
            icon[19]= new ImageIcon("icon/10.png");
            
            Random current = new Random();
            int count = current.nextInt(18)+1;
            keep[0] = count;
            for(int i=1;i<keep.length;i++)
            {
                count = current.nextInt(20);
                for(int j=0;j<i;j++)
                {
                    if(keep[j]==count)
                    {
                        i--;
                        break;
                    }
                    else
                    {
                        keep[i]=count;
                    }
                }
            }
            jButton1.setIcon(icon[keep[0]]);
            jButton2.setIcon(icon[keep[1]]);
            jButton3.setIcon(icon[keep[2]]);
            jButton4.setIcon(icon[keep[3]]);
            jButton5.setIcon(icon[keep[4]]);
            jButton6.setIcon(icon[keep[5]]);
            jButton7.setIcon(icon[keep[6]]);
            jButton8.setIcon(icon[keep[7]]);
            jButton9.setIcon(icon[keep[8]]);
            jButton10.setIcon(icon[keep[9]]);
            jButton11.setIcon(icon[keep[10]]);
            jButton12.setIcon(icon[keep[11]]);
            jButton13.setIcon(icon[keep[12]]);
            jButton14.setIcon(icon[keep[13]]);
            jButton15.setIcon(icon[keep[14]]);
            jButton16.setIcon(icon[keep[15]]);
            jButton17.setIcon(icon[keep[16]]);
            jButton18.setIcon(icon[keep[17]]);
            jButton19.setIcon(icon[keep[18]]);
            jButton20.setIcon(icon[keep[19]]);
            
            
            Timer t = new Timer(2500,new ActionListener(){
                public void actionPerformed(ActionEvent e){
                    
                    jButton1.setIcon(null);
                    jButton2.setIcon(null);
                    jButton3.setIcon(null);
                    jButton4.setIcon(null);
                    jButton5.setIcon(null);
                    jButton6.setIcon(null);
                    jButton7.setIcon(null);
                    jButton8.setIcon(null);
                    jButton9.setIcon(null);
                    jButton10.setIcon(null);
                    jButton11.setIcon(null);
                    jButton12.setIcon(null);
                    jButton13.setIcon(null);
                    jButton14.setIcon(null);
                    jButton15.setIcon(null);
                    jButton16.setIcon(null);
                    jButton17.setIcon(null);
                    jButton18.setIcon(null);
                    jButton19.setIcon(null);
                    jButton20.setIcon(null);
                    
                }
            });
            t.setRepeats(false);
            t.start();
            
            
           
        
        
        }
}
